[functions]
  directory = "functions/"

[build.environment]
  NODE_VERSION = "16.5.0"
  AWS_LAMBDA_JS_RUNTIME = "16.5.0"

[[headers]]
  for = "/[csv,geojson]/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"