import React from 'react';
import { Tooltip } from '../components';

// Helper function to clean bins generated by JsGeoDa
// Not Used
const BinsList = (props) => {
    let bins = props.data;
    // Check if bins are jenks generated with last bin >N
    if (bins.slice(-1,)[0] === '>'+bins.slice(-2,-1)[0]) {
        bins.splice(-2,1)
    }
    // Return div with bins, tooltip if using
    return (
        (bins.map((bin, index) => 
            <div className={`bin label ${bins.some(bin => bin.indexOf('tooltip')!== -1) ? 'tooltipText' : ''}`} key={`${bin}_${index}`}>
                {bin.indexOf('tooltip') === -1 && bin}
                {bin.indexOf('tooltip') !== -1 && <span>{bin.split(' tooltip:')[0]}<Tooltip id={bin.split(' tooltip:')[1]} /></span>}
            </div>
            )
        )
    )
}

export default BinsList;