# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dotDensityFlat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dotDensityFlat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64otDensityFlat.proto\"\x12\n\x03\x44ot\x12\x0b\n\x03val\x18\x01 \x03(\x05\x62\x06proto3'
)




_DOT = _descriptor.Descriptor(
  name='Dot',
  full_name='Dot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Dot.val', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['Dot'] = _DOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dot = _reflection.GeneratedProtocolMessageType('Dot', (_message.Message,), {
  'DESCRIPTOR' : _DOT,
  '__module__' : 'dotDensityFlat_pb2'
  # @@protoc_insertion_point(class_scope:Dot)
  })
_sym_db.RegisterMessage(Dot)


# @@protoc_insertion_point(module_scope)
