name: Vax, Hybrid, Pbf, and Summarize 0.0.2b

on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r data-scripts/requirements.txt
          
      - name: execute cdc vaccination data
        run: python data-scripts/cdc/getCdcVaccinationData.py
        
      - name: execute hybrid update
        run: python data-scripts/cdc/hybrid_update.py  

      - name: execute pbf
        run: python data-scripts/pbf/CsvToPbf.py  

      - name: execute summarize
        run: python data-scripts/summary/summarize.py  

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update Summary Data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
